[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "hoin-insight"
version = "0.0.1"
requires-python = ">=3.11"
dependencies = [
  "pandas",
  "matplotlib",
  "pyyaml",
  "requests",
  "yfinance",
  "youtube-transcript-api",
  "yt-dlp",
]
